version: '3.5'
services:
  django:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
    - /app/media
    - /app/log
    - /tmp
    environment:
    - HOST
    - PROTO
    - ADMINS
    - BASICAUTH_ENABLE
    - CI_ENVIRONMENT_NAME
    - CI_COMMIT_SHA
    - SENTRY_DSN
    - MEDIA_ROOT=/app/media
    - LOG_DIR=/app/log
    - DB_HOST=postgres
    - DB_NAME=django
    - DB_USER=django
    - DB_PASS=django
    - DB_ENGINE=django.db.backends.postgresql
    - EMAIL_HOST
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
    - EMAIL_USE_SSL
    - EMAIL_USE_TLS
    - EMAIL_PORT
    - DEFAULT_FROM_EMAIL
    - SECRET_KEY

  postgres:
    image: postgres:13
    environment:
    - POSTGRES_DB=django
    - POSTGRES_USER=django
    - POSTGRES_PASSWORD=django
    volumes:
    - /var/lib/postgresql/data
