version: "3.5"
services:
  django:
    # DO NOT REMOVE
    # Ensures we keep access logs accross re-creates of the container
    # Use journalctl CONTAINER_NAME=production_backend_1 to see them
    logging:
      driver: journald
    restart: always
    volumes:
      - ./data/media:/app/media
      - ./spooler:/spooler
      - ./log:/app/log
    labels:
      - "io.yourlabs.compose.mkdir=/spooler,./data/media,./log,:1000:1000:0750"
      - "traefik.http.middlewares.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-redirect.redirectregex.regex=^https?://${HOST}/(.*)"
      - "traefik.http.middlewares.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-redirect.redirectregex.replacement=https://www.${HOST}/$${1}"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-ssl.middlewares=${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-redirect"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-ssl.entryPoints=websecure"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-ssl.rule=host(`${HOST}`, `www.${HOST}`)"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-ssl.tls=true"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-ssl.tls.certResolver=leresolver"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-ssl.service=${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-ssl"
      - "traefik.http.services.${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-ssl.loadBalancer.server.port=8000"
      - "traefik.docker.network=web"
    networks:
      - web
      - default

  postgres:
    logging:
      driver: journald
    restart: always
    networks:
      - default
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./dump:/dump
    labels:
      - "io.yourlabs.compose.mkdir=./dump,./data/postgres,./log/postgres:999:999:0700"

networks:
  web:
    external: true

