---

- name: Set home for project
  when: home is not defined
  set_fact:
    home: '{{ ansible_user_dir + "/.yourlabs.compose/" + project|default("default") }}'

- name:
  docker_compose:
    remove_orphans: yes
    state: absent
    remove_images: all
    remove_orphans: yes
    remove_volumes: yes
    services: '{{ services|default("") }}'
    project_src: '{{ home }}'
