---

- name: Ensure docker was setup once on this host
  include_role: name=yourlabs.docker
  when: ansible_facts['ansible_local']['yourlabs_docker']['state']|default('') != 'success'

- name: Make home directory
  file:
    path: '{{ home }}'
    state: directory

- name: Download compose file if URL
  when: compose.startswith('https://') or compose.startswith('http://')
  delegate_to: localhost
  get_url:
    url: '{{ compose }}'
    dest: '{{ home }}/docker-compose.yml'

- name: Get the docker networks list
  shell: docker network ls --format '{{ "{{ .Name }}" }}'
  changed_when: false
  register: docker_network_ls

- name: Generate docker-compose.yml
  set_fact:
    compose_content: '{{ (compose if not compose.startswith("http") else "docker-compose.yml")|docker_compose_rewrite(hostvars[inventory_hostname], docker_network_ls.stdout_lines) }}'

- name: Get external networks from compose contents
  set_fact:
    external_networks: '{{ compose_content|docker_compose_external_networks }}'

- name: Create docker networks
  docker_network:
    name: '{{ item }}'
  loop: '{{ external_networks }}'

- name: Upload compose file
  copy:
    content: '{{ compose_content }}'
    dest: '{{ home }}/docker-compose.yml'

- name: Login to docker registry
  when: docker_auth_username|default(false)
  docker_login:
    username: '{{ docker_auth_username }}'
    password: '{{ docker_auth_password }}'
    registry: '{{ docker_auth_registry|default("hub.docker.io") }}'

- name: Run docker-compose
  docker_compose:
    project_src: '{{ home }}'
    restarted: true
    build: '{{ build|default("no") }}'

- name: Show logs
  shell: docker-compose logs
  args:
    chdir: '{{ home }}'
