---

- name: Setup project lifetime
  copy:
    content: '{{ lookup("pipe", "date +%s")|int + lifetime|int }}'
    dest: '{{ home }}/removeat'

- name: Make /root/.yourlabs.compose for ephemeral deploys
  file:
    path: /root/.yourlabs.compose
    state: directory

- name: Install cleaning script
  copy:
    src: remove.sh
    dest: /root/.yourlabs.compose/remove.sh
    mode: u+rwx,g-rwx,o-rwx

- name: Setup cron
  include_role: name=yourlabs.timer
  vars:
    name: 'yourlabs-compose-cleaner'
    cmd: /root/.yourlabs.compose/remove.sh
    oncalendar: '*-*-* *:*:*'
